Create Table MB_DEV.XXCT_SERVICE_INVOKE_LOG
(
 SEQUENCE_ID Number Not Null,
 START_DATE Varchar2(30),
 END_DATE Varchar2(30),
 SERVICE_NAME Varchar2(100),
 WSDL_URL Varchar2(250),
 REQUEST_PAYLOAD CLOB,
 AUTH_STR Varchar2(250),
 REQUEST_PROPERTY Varchar2(4000),
 REQUEST_METHOD Varchar2(100),
 REQUEST_PAYLOAD_LENGTH Varchar2(4000),
 RESPONSE_CODE Varchar2(100),
 RESPONSE_MESSAGE Varchar2(4000),
 RESPONSE_PAYLOAD CLOB,
 PROCESS_STATUS Varchar2(30) Default 'PENDING',
 PROCESS_MESSAGE Varchar2(4000),
 SOURCE_SYSTEM Varchar2(100),
 DESTINATION_SYSTEM Varchar2(100),
 OBJECT_ID Varchar2(100),
 OBJECT_SOURCE Varchar2(100),
 GROUP_ID Varchar2(100),
 ROW_VERSION_NUMBER Number Default 1,
 CREATION_DATE DATE default sysdate not null,
 CREATED_BY NUMBER default -1 not null,
 LAST_UPDATED_BY NUMBER default -1 not null,
 LAST_UPDATE_DATE DATE default sysdate not null,
 LAST_UPDATE_LOGIN NUMBER,
 PROGRAM_APPLICATION_ID NUMBER,
 PROGRAM_ID NUMBER,
 PROGRAM_UPDATE_DATE DATE,
 REQUEST_ID NUMBER,
 ATTRIBUTE_CATEGORY VARCHAR2(30),
 ATTRIBUTE1 VARCHAR2(240),
 ATTRIBUTE2 VARCHAR2(240),
 ATTRIBUTE3 VARCHAR2(240),
 ATTRIBUTE4 VARCHAR2(240),
 ATTRIBUTE5 VARCHAR2(240),
 ATTRIBUTE6 VARCHAR2(240),
 ATTRIBUTE7 VARCHAR2(240),
 ATTRIBUTE8 VARCHAR2(240),
 ATTRIBUTE9 VARCHAR2(240),
 ATTRIBUTE10 VARCHAR2(240),
 ATTRIBUTE11 VARCHAR2(240),
 ATTRIBUTE12 VARCHAR2(240),
 ATTRIBUTE13 VARCHAR2(240),
 ATTRIBUTE14 VARCHAR2(240),
 ATTRIBUTE15 VARCHAR2(240)
);
comment on table MB_DEV.XXCT_SERVICE_INVOKE_LOG is '接口调用记录表';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.SEQUENCE_ID is '表ID，主键，供其他表做外键';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.START_DATE is '开始时间';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.END_DATE is '结束时间';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.SERVICE_NAME is '服务名称';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.WSDL_URL is '服务地址';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.REQUEST_PAYLOAD is '请求的报文';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.AUTH_STR is '认证信息';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.REQUEST_PROPERTY is '请求的属性';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.REQUEST_METHOD is '请求方法';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.REQUEST_PAYLOAD_LENGTH is '报文长度';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.RESPONSE_CODE is '请求返回状态';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.RESPONSE_MESSAGE is '请求返回的消息';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.RESPONSE_PAYLOAD is '请求返回的报文';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.PROCESS_STATUS is '后台处理状态，约定：
ENTER/数据正在录入，用户可以修改
PENDING/用户已确认，数据可以导入
SKIP/不需要做接口处理
ERROR/出错，数据验证不通过
COMPLETE/数据已经进入接口，用户不可以修改';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.PROCESS_MESSAGE is '处理消息';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.SOURCE_SYSTEM is '来源系统';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.DESTINATION_SYSTEM is '目标系统';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.OBJECT_ID is '来源标识';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.OBJECT_SOURCE is '来源说明';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.GROUP_ID is '批次ID';
comment on column MB_DEV.XXCT_SERVICE_INVOKE_LOG.ROW_VERSION_NUMBER is '行版本号，用来处理锁';

alter table MB_DEV.XXCT_SERVICE_INVOKE_LOG add constraint XXCT_SERVICE_INVOKE_LOG_PK primary key (SEQUENCE_ID);
Create Index MB_DEV.XXCT_SERVICE_INVOKE_LOG_N1 On MB_DEV.XXCT_SERVICE_INVOKE_LOG(OBJECT_ID,OBJECT_SOURCE) tablespace APPS_TS_TX_IDX;

Create Sequence MB_DEV.XXCT_SERVICE_INVOKE_LOG_S Start With 10001;
