--1.Create db user
create user C##MB_DEV identified by M#bike20170801;
--2.Grant access
grant connect, resource,dba to C##MB_DEV;
--3.Create Table
CREATE TABLE C##MB_DEV.XXCT_USER (
  ID NUMBER NOT NULL ,
  USER_NAME VARCHAR2(100) DEFAULT NULL,
  PASSWORD VARCHAR2(100) DEFAULT NULL,
  ROLE_NAME VARCHAR(20) DEFAULT NULL);

CREATE SEQUENCE C##MB_DEV.XXCT_USER_S START WITH 1 NOCACHE;